Repository openshift/ksan-operator, pull requests merged in 2024-12, with the labels that each got.

#5 NOJIRA: fix: updating the makefile go install command for ci, making tests ve…
  Makefile
  hack/publish-codecov.sh
Labels: lgtm

#8 OCPEDGE-1422: feat(CRD): update CRD objects
  PROJECT
  api/v1alpha1/ksannode_types.go
  api/v1alpha1/ksanstorage_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/ksan.openshift.io_ksannodes.yaml
  config/crd/bases/ksan.openshift.io_ksanstorages.yaml
  config/crd/kustomization.yaml
  config/rbac/ksannode_editor_role.yaml
  config/rbac/ksannode_viewer_role.yaml
  config/rbac/kustomization.yaml
  config/samples/ksan_v1alpha1_ksannode.yaml
  config/samples/kustomization.yaml
  internal/controller/ksanstorage_controller_test.go
Labels: approved, lgtm, size/L, jira/valid-reference

#9 OCPEDGE-1424: feat(controller): Create KSANNode objects
  api/v1alpha1/ksannode_types.go
  api/v1alpha1/ksanstorage_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/ksan.openshift.io_ksannodes.yaml
  config/crd/bases/ksan.openshift.io_ksanstorages.yaml
  go.mod
  go.sum
  internal/controller/ksan_node.go
  internal/controller/ksanstorage_controller.go
  internal/controller/node_selector.go
  vendor/k8s.io/apiserver/pkg/util/version/version.go
  vendor/k8s.io/component-helpers/LICENSE
  vendor/k8s.io/component-helpers/scheduling/corev1/doc.go
  vendor/k8s.io/component-helpers/scheduling/corev1/helpers.go
  vendor/k8s.io/component-helpers/scheduling/corev1/nodeaffinity/nodeaffinity.go
  vendor/modules.txt
Labels: approved, lgtm, jira/valid-reference, size/XXL
